package com.example.domain.entity.remote

data class Hour(

    val time_epoch: Long,
    val time: String,
    val temp_c: Double,
    val temp_f: Double,
    val is_day: Long,
    val condition: Condition3,
    val wind_mph: Double,
    val wind_kph: Double,
    val wind_degree: Long,
    val wind_dir: String,
    val pressure_mb: Double,
    val pressure_in: Double,
    val precip_mm: Double,
    val precip_in: Double,
    //val snow_cm: Double,
    val humidity: Long,
    val cloud: Long,
    val feelslike_c: Double,
    val feelslike_f: Double,
    val windchill_c: Double,
    val windchill_f: Double,
    val heatindex_c: Double,
    val heatindex_f: Double,
    val dewpoint_c: Double,
    val dewpoint_f: Double,
    val will_it_rain: Long,
    val chance_of_rain: Long,
    val will_it_snow: Long,
    val chance_of_snow: Long,
    val vis_km: Double,
    val vis_miles: Double,
    val gust_mph: Double,
    val gust_kph: Double,
    val uv: Double,
)
data class Condition3(
    val text: String,
    val icon: String,
    val code: Long,
)